### ISSUE TITLE
Plural queries

### ISSUE THREAD

**Issue by whiplash** [mhart/simple-relay-starter#1]
Hi and thanks for you super easy starter.

I'm trying to do the same with the only difference that my query returns an array of "things" that I then want to map onto the component's props.

I was wondering if you had such an example.

Reading around a bit I've found a lot of people talking about it (using either `@relay(plular: true)`) and also an [issue](https://github.com/facebook/relay/issues/112) explaining how this should be handled but I couldn't it make it work on my case.

Thanks you.

**Comment by mhart** [comment]
Hi @whiplash – this issue isn't really related to this project so I'm going to close it – I hope you found the answers you were looking for elsewhere!
